format = 1
base_url = "https://origami-dist.irix.fans/irix/"
sets = ["6.5.30", "foundations", "development", "applications", "complementary"]
[package_selections.base]
install = []
keep = []

[package_selections.desktop]
install = []
keep = ["inventor_dev", "java2_plugin.sw32.mozilla_freeware", "java_dev.sw32.binaries"]

[package_selections.development]
install = ["c_fe.sw.c", "c_dev.sw.c", "compiler_dev.sw.base", "compiler_dev.sw.ld", "dev.sw.lib"]
keep = ["java2_plugin.sw32.mozilla_freeware", "java_dev.sw32.binaries"]

[collisions.development]
"development/dist/inst.README" = "mipspro744update"

[replacements.development]
devfoundation = "mipspro744update"

[[layers]]
set = "6.5.30"
name = "overlays1"
path = "6.5.30/overlays1.image"
remote_path = "6.5.30/overlays1.iso"
boot = true

[[layers]]
set = "6.5.30"
name = "overlays2"
path = "6.5.30/overlays2.image"
remote_path = "6.5.30/overlays2.iso"
boot = false

[[layers]]
set = "6.5.30"
name = "overlays3"
path = "6.5.30/overlays3.image"
remote_path = "6.5.30/overlays3.iso"
boot = false

[[layers]]
set = "foundations"
name = "foundation1"
path = "6.5-base/foundation1.image"
remote_path = "6.5-base/foundation1.iso"
boot = false

[[layers]]
set = "foundations"
name = "foundation2"
path = "6.5-base/foundation2.image"
remote_path = "6.5-base/foundation2.iso"
boot = false

[[layers]]
set = "foundations"
name = "onc3-nfs"
path = "6.5-base/nfs.image"
remote_path = "6.5-base/nfs.iso"
boot = false
dist = "dist6.5"

[[layers]]
set = "development"
name = "devlibs"
path = "6.5-base/devlibs.image"
remote_path = "6.5-base/devlibs.iso"
boot = false

[[layers]]
set = "development"
name = "devfoundation"
path = "6.5-base/devfoundation.image"
remote_path = "6.5-base/devfoundation.iso"
boot = false
dist = "dist/dist6.5"

[[layers]]
set = "development"
name = "mipspro744update"
path = "mipspro/7.4.4/mipspro744update.tar.gz"
boot = false
base = "MIPSPro7.4.4"
dist = "."

[[layers]]
set = "development"
name = "mipspro_c"
path = "mipspro/7.4.4/mipspro_c.tar.gz"
boot = false
base = "mipspro_c"
dist = "dist"

[[layers]]
set = "applications"
name = "applications"
path = "6.5.30/applications.image"
remote_path = "6.5.30/applications.iso"
boot = false

[[layers]]
set = "complementary"
name = "complementary"
path = "6.5.30/complementary.image"
remote_path = "6.5.30/complementary.iso"
boot = false
